name: PR workflow

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (Clone the repo to this runner)
        uses: actions/checkout@v3

      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: mvn build

      - name: Test
        run: mvn test

      - name: something for test
        run: echo "Hello world!"
        